language: node_js
node_js:
  - 12
services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed ducnhudaik/udagram-api-feed
  - docker tag udagram-api-user ducnhudaik/udagram-api-user
  - docker tag udagram-frontend ducnhudaik/udagram-frontend
  - docker tag reverseproxy ducnhudaik/reverseproxy
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ducnhudaik/udagram-api-feed
  - docker push ducnhudaik/udagram-api-user
  - docker push ducnhudaik/udagram-frontend
  - docker push ducnhudaik/reverseproxy
